- alias: "Backroom Lights On"
  trigger:
    - platform: state
      entity_id: binary_sensor.backroom_pir_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: scene.backroom_lights_on

- alias: "Backroom Lights off"
  trigger:
    - platform: state
      entity_id: binary_sensor.backroom_pir_sensor
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  condition:
    condition: time
    after: '23:00:00'
    before: '17:00:00' 
  action:
    service: homeassistant.turn_on
    entity_id: scene.backroom_lights_off

- alias: "Bedroom Lights on"
  trigger:
    - platform: time
      at: '06:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_on
    entity_id: scene.bedroom_lights_on

- alias: "Bedroom Lights off"
  trigger:
    platform: state
    entity_id: switch.aeotec_wallwart_1_switch
    to: 'on'
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition:
    condition: or
    conditions:
      - condition: time
        after: '23:00:00'
        before: '06:00:00'
      - condition: time
        after: '08:00:00'
        before: '18:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: scene.bedroom_lights_off

- alias: "Kettle Boiled"
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.kettle_on
      to: 'off'
  action:   
    - service: tts.google_say
      entity_id: media_player.allspeakers
      data:
        message: 'Kettles Boiled'

- alias: "Turn off Kettle Boiled Detection"
  trigger:
    - platform: state
      entity_id: binary_sensor.kettle_on
      to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: automation.kettle_boiled

- alias: "Turn on Kettle boiled detection"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kettle_on                                                                                                                                                           
      to: 'on'                                                                                                                                                                                    
      for:                                                                                                                                                                                
        seconds: 30     
  action:
    service: homeassistant.turn_on
    entity_id: automation.kettle_boiled

#####################
- alias: "Toast 1 Ready"
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.toaster_on
      to: 'off'
  action:
    - service: tts.google_say
      entity_id: media_player.allspeakers
      data:
        message: 'Toaster Side 1 has popped'

- alias: "Toast 2 Ready"
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.toaster_all_on
      to: 'off'
  action:
    - service: tts.google_say
      entity_id: media_player.allspeakers
      data:
        message: 'Toaster Side 2 has popped'

- alias: "Turn on Toast Side 1"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.toaster_on
      to: 'on'
      for:
        seconds: 30
  action:
    service: homeassistant.turn_on
    entity_id: automation.toast_1_ready

- alias: "Turn on Toast Side 2"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.toaster_all_on
      to: 'on'
      for:
        seconds: 30
  action:
    service: homeassistant.turn_on
    entity_id: automation.toast_2_ready

- alias: "Turn off Toast Side 1"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.toaster_on
      to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: automation.toast_1_ready

- alias: "Turn off Toast Side 2"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.toaster_all_on
      to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: automation.toast_2_ready

