- alias: "Backroom Lights On"
  trigger:
    - platform: state
      entity_id: binary_sensor.backroom_pir_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: scene.backroom_lights_on

- alias: "Backroom Lights off"
  trigger:
    - platform: state
      entity_id: binary_sensor.backroom_pir_sensor
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  condition:
    - condition: time
      after: '23:00:00'
      before: '19:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: scene.backroom_lights_off
