homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml

frontend:
config:
map:
http:
  api_password: !secret http_passwd 
  base_url: !secret http_base_url
updater:
  # include_used_components: true
discovery:
history:
logbook:

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_usr
  password: !secret influxdb_pass

recorder:
  db_url: !secret pg_db_url
  #purge_interval: 10
  #purge_keep_days: 90

sun:

zwave:
  usb_path: /dev/ttyACM1
#  network_key: !secret zw_netkey

weather:
  - platform: yweather

# Text to speech
tts:
  - platform: google

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password

google_assistant:
  project_id: !secret gha_proj_id
  client_id: !secret gha_client_id
  access_token: !secret gha_access_tok
  api_key: !secret gha_api_key
  expose_by_default: true
  
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
scene: !include scenes.yaml
